package com.e_commerce.product_service.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
//constructors, getters, setters, toString, equals, hashCode
@AllArgsConstructor
// @NoArgsConstructor generates a constructor with no parameters. If any final fields exist, they will be initialized with 0 / false / null.
@NoArgsConstructor
// @Builder is a design pattern that allows for the creation of complex objects step by step. It provides a flexible and readable way to construct objects, especially when they have many parameters or optional fields. The @Builder annotation in Lombok generates a builder class for the annotated class, allowing you to create instances of the class using a fluent API.
@Builder
// @Data is a convenient shortcut annotation that bundles the features of @ToString, @EqualsAndHashCode, @Getter / @Setter and @RequiredArgsConstructor together. In other words, @Data generates all the boilerplate that is normally associated with simple POJOs (Plain Old Java Objects) and beans: getters for all fields, setters for all non-final fields, and appropriate toString, equals and hashCode implementations that involve the fields of the class.
@Data
@Document(collection = "products")
public class Product {
    // unique id for all products, generated by MongoDB
    @Id
    private String id;
    private String name;
    private String description;
    private double price;
    private int quantity;
    
}
